{% set name = "adaptive" %}
{% set version = "0.7.5" %}
{% set sha256 = "50f1f959420e591e998a50704cdcb7a0928afcb705dd8632a0d0b5219f5d01a7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.zip
  url: https://github.com/python-adaptive/adaptive/archive/v{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - bokeh
    - scipy
    - holoviews >=1.9.1
    - ipywidgets
    - ipython
    - ipykernel >=4.8.0
    - jupyter_client >=5.2.2
    - sortedcontainers
    - sortedcollections
    - matplotlib

test:
  imports:
    - adaptive

about:
  home: http://github.com/python-adaptive/adaptive
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Adaptive parallel sampling of mathematical functions'
  description: |
    adaptive is an open-source Python library designed to make adaptive
    parallel function evaluation simple. With adaptive you just supply a
    function with its bounds, and it will be evaluated at the "best" points
    in parameter space. With just a few lines of code you can evaluate
    functions on a computing cluster, live-plot the data as it returns,
    and fine-tune the adaptive sampling algorithm.
  doc_url: http://adaptive.readthedocs.org
  dev_url: https://github.com/python-adaptive/adaptive/

extra:
  recipe-maintainers:
    - basnijholt
    - jbweston
    - akhmerov
