appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NmYlBKiNBq5cy7QfFS2MJ41CI8zxRzdwajCipbwhg+M3Qsda/wNZZA5g401JXmpb4NK0e1LQQ2r2kxTjB/OX2j9K9RtsYhbkEMuMuMAA97jKa9a0tkhBcy74fhpJcaPEGaq5rrhWbapn4cdYpw9bShfQRFiGFhVqSxiwKK08itJ+woFtOZ0R9vTqoCi7BflXEyLc57Rs0KBMmEA6Fx2W5eprayHYShNN6pG4Ru90tr7ARkzrPXJl7hRQvfWb2BU/AKioyHYzeix694arXVXjzOob3bGbYVCRfOVLVQPNFwO3q4E5bbNSKhK+Qgss3KjeQk6RcB5/spSMUgMQ/6Cf8M0hx/mC1WDs+k6hJjbqbb8mR2ueLQ/rARW3kOZBHxPd1XZL0y3G0EYXhQwMVlC4VEKW1p8/sl6pjrg+4IezTHkgp8f1IUy4FrZFsw3VeUTQLftVDfsHP4iLvAawVS3dOvg79ZZYi8aPsU8kak2KuzCGkEEAUQNLdBx94RbUZDKMD8c9sGLbuQECRUyoCJFk7gU5sLXSNLP4T8S6utvMPJJ0TBtZn/gBCrp0xpREZdYJpHIuud4Eq+Y2kkNsD65mPRAk1hTuRfhJtDoVtxKLPAyAmsWYs7UA8/6dKkGegkUPsciaDHrpqVH0noDmjPBNezjx5BV1Y4dNzqGdSx88xnI=}
provider:
  win: azure
conda_forge_output_validation: true
